version: "3.7"

services:
  react-frontend:
    image: node:14
    command: sh -c "cd /reactmovieapp/src; npm start"
    ports: 
      - "3000:3000"
    environment:
      NODE_DOCKER: "true"
      ENVIRONMENT: "LOCAL_DEV"
      SERVER: "LOCALHOST"
    working_dir: /reactmovieapp
    deploy:
      resources:
        limits:
          memory: "${NODE_MEM}"
        reservations:
          memory: "${NODE_MEM_RES}"
          cpus: "${NODE_CPU_SHARE}"
    volumes: 
      - ../reactmovieapp:/reactmovieapp
    stdin_open: true 