version: "3.7"

services:
  movie-api-database:
    build: 
        context: ../movieappdatabase/src
        dockerfile: database.Dockerfile
    image: movie-app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdatabase:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: "${DATABASE_MEM}"
        reservations:
          memory: "${DATABASE_MEM_RES}"
          cpus: "${DATABASE_CPU_SHARE}"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: "${REDIS_MEM}"
        reservations:
          memory: "${REDIS_MEM_RES}"
          cpus: "${REDIS_CPU_SHARE}"

  redis-listener:
    image: python-engine
    profiles:
      - redis
    environment:
      SERVER: "LOCALHOST"
      ENVIRONMENT: "LOCAL-DEV"
    volumes:
      - ./src/AutomatedScripts:/home/AutomatedScripts
    command: python3 -m AutomatedScripts.Scripts.ScriptController -path AutomatedScripts.Scripts.Redis.redisListener -jobId 2 -stepId 2 -dbConnectionRetryAttempts 1
    deploy:
      resources:
        limits:
          memory: "${REDIS_LISTENER_MEM}"
        reservations:
          memory: "${REDIS_LISTENER_MEM_RES}"
          cpus: "${REDIS_LISTENER_CPU_SHARE}"
      restart_policy:
        condition: any
        delay: 5s
    depends_on:
      - movie-api-database
      - redis

volumes:
  pgdatabase:
