version: "3.7"

services:
  redis-container:
    image: 'redis'
    ports:
      - "6739:6739"
    expose:
      - 6739
  movie-api-app:
    image: node:14
    command: sh -c "npm run server"
    ports:
      - "9000:9000"
    environment:
      NODE_DOCKER: "true"
      NODE_ENV: "dev"
    working_dir: /movie-app-api
    volumes:
      - ./:/movie-app-api
    
